name: Deploy Cloud Run

on:
  push:
    branches:
      - 'staging'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker ${{ secrets.GOOGLE_AUTH }}
          docker build -t ${{ secrets.ARTIFACT_REGISTRY }}/${{ secrets.SERVICE_NAME }} .
          docker push ${{ secrets.ARTIFACT_REGISTRY }}/${{ secrets.SERVICE_NAME }}

      - name: deploy to cloud run
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud run deploy ${{ secrets.SERVICE_NAME }} --image="${{ secrets.ARTIFACT_REGISTRY }}/${{ secrets.SERVICE_NAME }}:${{ secrets.SERVICE_VERSION }}" --set-env-vars="NODE_ENV=${{ secrets.SERVICE_ENV }}" --set-env-vars="APP_HOST=${{ secrets.SERVICE_HOST }}" --set-env-vars="APP_PORT=${{ secrets.SERVICE_PORT }}" --set-env-vars="APP_PREFIX=${{ secrets.SERVICE_PREFIX }}" --set-env-vars="DB_HOST=${{ secrets.DB_HOST }}" --set-env-vars="DB_PORT=${{ secrets.DB_PORT }}" --set-env-vars="DB_NAME=${{ secrets.DB_NAME }}" --set-env-vars="DB_USER=${{ secrets.DB_USER }}" --set-env-vars="DB_PASS=${{ secrets.DB_PASS }}" --set-env-vars="REDIS_HOST=${{ secrets.REDIS_HOST }}" --set-env-vars="REDIS_PORT=${{ secrets.REDIS_PORT }}" --region="${{ secrets.SERVICE_REGION }}" --project="${{ secrets.PROJECT_ID }}
          gcloud run services update-traffic ${{ secrets.SERVICE_NAME }} --region="${{ secrets.SERVICE_REGION }}" --to-latest
          curl -H "Content-Type: application/json" -X POST -d '{"username": "${{ secrets.DISCORD_WEBHOOK_USERNAME }}","avatar_url": "${{ secrets.DISCORD_WEBHOOK_AVATAR_URL }}","embeds": [{"title": "Service Deployed: '${{ secrets.SERVICE_NAME }}'","description": "Service '${{ secrets.SERVICE_NAME }}' has been updated to the latest revision Traffic has been routed to the latest revision **Project ID**: `'${{ secrets.PROJECT_ID }}'` **NODE_ENV**: `'${{ secrets.SERVICE_ENV }}'` **APP_HOST**: `'${{ secrets.SERVICE_HOST }}'` **APP_PORT**: `'${{ secrets.SERVICE_PORT }}'` **APP_PREFIX**: `'${{ secrets.SERVICE_PREFIX }}'` **DB_HOST**: `'${{ secrets.DB_HOST }}'` **DB_PORT**: `'${{ secrets.DB_PORT }}'` **DB_NAME**: `'${{ secrets.DB_NAME }}'` **DB_USER**: `'${{ secrets.DB_USER }}'` **REDIS_HOST**: `'${{ secrets.REDIS_HOST }}'` **REDIS_PORT**: `'${{ secrets.REDIS_PORT }}'` ", "color": 65280}]}' ${{ secrets.DISCORD_WEBHOOK_URL }} echo "Service deployed to Cloud Run"
